apiVersion: v1
entries:
  morgenruf:
  - apiVersion: v2
    appVersion: 1.1.2
    created: "2026-04-07T10:37:51.357438634Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 18.5.15
    description: Self-hosted Slack standup bot with PostgreSQL
    digest: 2d28bb0176e71da5788a1ca8df1d3fade84689a7928c6dc5aca3ff2b718fddff
    home: https://morgenruf.dev
    keywords:
    - slack
    - standup
    - bot
    maintainers:
    - email: hello@morgenruf.dev
      name: morgenruf
      url: https://morgenruf.dev
    name: morgenruf
    sources:
    - https://github.com/morgenruf/morgenruf
    type: application
    urls:
    - https://charts.morgenruf.dev/charts/morgenruf-0.4.0.tgz
    version: 0.4.0
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-04-07T10:37:51.351271693Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 18.5.15
    description: Self-hosted Slack standup bot with PostgreSQL
    digest: c28e611ef8cf0f71c1c940d6016ee43a3aa90b83d6c19cea32473b7f6176c521
    home: https://morgenruf.dev
    keywords:
    - slack
    - standup
    - bot
    maintainers:
    - email: hello@morgenruf.dev
      name: morgenruf
      url: https://morgenruf.dev
    name: morgenruf
    sources:
    - https://github.com/morgenruf/morgenruf
    type: application
    urls:
    - https://charts.morgenruf.dev/charts/morgenruf-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-04-07T10:37:51.345106057Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 15.x.x
    description: Self-hosted Slack standup bot with PostgreSQL
    digest: 128d9f5dd05a8c9728f64b6561045a7d40e54eb7dc4dee3c0e60f53f10f37b8c
    home: https://morgenruf.dev
    keywords:
    - slack
    - standup
    - bot
    maintainers:
    - email: hello@morgenruf.dev
      name: morgenruf
      url: https://morgenruf.dev
    name: morgenruf
    sources:
    - https://github.com/morgenruf/morgenruf
    type: application
    urls:
    - https://charts.morgenruf.dev/charts/morgenruf-0.2.0.tgz
    version: 0.2.0
generated: "2026-04-07T10:37:51.340262735Z"
