apiVersion: v1
entries:
  morgenruf:
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-04-05T03:51:15.131379452Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 15.x.x
    description: Self-hosted Slack standup bot with PostgreSQL
    digest: d5c4a06a4e1c64f9e622a1b444dbcd2a902984170af47d4f6a4f4f8857b90d17
    home: https://morgenruf.dev
    keywords:
    - slack
    - standup
    - bot
    maintainers:
    - email: hello@morgenruf.dev
      name: morgenruf
      url: https://morgenruf.dev
    name: morgenruf
    sources:
    - https://github.com/morgenruf/morgenruf
    type: application
    urls:
    - https://charts.morgenruf.dev/charts/morgenruf-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 1.0.0
    created: "2026-04-05T03:51:15.125686122Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 15.x.x
    description: Self-hosted Slack standup bot with PostgreSQL
    digest: 128d9f5dd05a8c9728f64b6561045a7d40e54eb7dc4dee3c0e60f53f10f37b8c
    home: https://morgenruf.dev
    keywords:
    - slack
    - standup
    - bot
    maintainers:
    - email: hello@morgenruf.dev
      name: morgenruf
      url: https://morgenruf.dev
    name: morgenruf
    sources:
    - https://github.com/morgenruf/morgenruf
    type: application
    urls:
    - https://charts.morgenruf.dev/charts/morgenruf-0.2.0.tgz
    version: 0.2.0
generated: "2026-04-05T03:51:15.119839911Z"
